version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  post_build:
    commands:
      - mvn package
      - mv target/spring-mvc-showcase.war spring-mvc-showcase.war
artifacts:
  files:
    - spring-mvc-showcase.war
    - .ebextensions/**/*